### ISSUE TITLE
The coordinate system in use

### ISSUE THREAD

**Issue by shifanakoya** [johan12345/gcs_python#13]
Hi
I would like to the default coordinate system in use in GCS python. I
 could see that in the table of validation of GCS IDL and GCS Python u have used Stonyhurst Longitude 𝜙 [°] and Heliographic Latitude 𝜃 [°]. why switch between coordinates in GCS python?

If I have Heliographic Latitude 𝜃 [°] and Heliographic Longitude 𝜙 [°] fitted in IDL while comparing do I have to convert Heliographic Longitude 𝜙 [°] to Stonyhurst Longitude 𝜙 [°] and input that in GCS Python?

**Comment by johan12345** [comment]
*Heliographic longitude* is not an unambiguous definition of a coordinate system, you need some reference point for the longitude. That can either be the *Stonyhurst* variant (0° longitude is at the Sun-Earth line) or the *Carrington* variant (0° longitude is at the Carrington prime meridian, which is defined by an arbitrary point in time). The latitude is the same in both coordinate systems, because it is defined by the solar equator, so it can simply be called "Heliographic latitude".

The GCS IDL implementation allows to switch between Carrington and Stonyhurst longitudes as far as I remember. The Python version only supports Stonyhurst coordinates so far, as that is what was most convenient for me when I used it. But it should be fairly straightforward to add support for switching to Carrington coordinates - basically, the coordinate frame would need to be made configurable in the [`gcs_mesh_sunpy`](https://github.com/johan12345/gcs_python/blob/451d6b92e8a5f84ac61f321a2c6034b746f94b10/gcs/geometry.py#L171) function (from `HeliographicStonyhurst` to `HeliographicCarrington`).

**Comment by shifanakoya** [comment]
Excellent, Thanks for the clarification.

**Comment by MohamedNedal** [comment]
Hello @johan12345 , I have a question regarding the coordinate system used in the GCS code. I see that the longitude doesn't accept negative values although it is Heliographic Stonyhurst system in which 0° longitude is at the Sun-Earth line. Instead, it takes values from 0 to 360 degrees. So what if I have a negative longitude, say -50 deg., How it should be represented? Should I add 360 deg. to it?

**Comment by johan12345** [comment]
The -180° to 180° or 0° to 360° representations are equivalent. So -50° would be the same as 360°-50° = 310°.

**Comment by MohamedNedal** [comment]
Thank you
