### ISSUE TITLE
About CME angular half width

### ISSUE THREAD

**Issue by MohamedNedal** [johan12345/gcs_python#7]
Hello, I'm using the DBEM model for predicting the CME arrival time and the valid values of the CME's angular half-width (AW/2) are: 
_0 deg. < AW/2 < 90 deg._ 

Can you please tell me how to model a Halo-CME, which has AW = 360 deg.? 
Is it correct to put the angular half-width to be 89 deg. for halo-CMEs?

**Comment by johan12345** [comment]
A halo CME (in almost all cases) does not have an actual angular width of 360°, that is just what it looks like from the Earth/L1 point of view, because it is coming towards Earth (or exactly opposite). The actual angular width can be determined with GCS, using at least one additional viewpoint away from the CME direction of travel.

**Comment by MohamedNedal** [comment]
Thank you
